### ISSUE TITLE
Pip version doesn't have latest bug fix

### ISSUE THREAD

**Issue by philass** [pepijndevos/futhark-pycffi#12]
I am using MacOS and tried installing this library via pip. However there was an issue with OpenCL. However when I pip installed from source it worked. It seems like the latest change fixes my problem. It would probably make sense to update the package (create a new release) so that when installed via pip, it contains the latest fix.

**Comment by pepijndevos** [comment]
Hrm, I'm not really using Futhark or this library at the moment. Maybe it'd be possible to set up a GH Action to publish to pypi? That way I can occasionally hit merge on some drive-by fixes without having to figure out how to update to the latest futhark and remember Python packaging commands.

**Comment by philass** [comment]
Totally understandable, and thanks for your response!

**Comment by pepijndevos** [comment]
It seems entirely possible to publish to PyPi automatically:
https://docs.travis-ci.com/user/languages/python/
https://docs.travis-ci.com/user/deployment/pypi/
Not really sure how that works with creating all the eggs and whatever. If you feel like experimenting with that, I'd be happy to add you as a maintainer to the PyPi package.

**Comment by philass** [comment]
Oh Cool! I'd definitely be willing and interested in figuring that out. Do you need any personal information (i.e email address)?

**Comment by pepijndevos** [comment]
I need a PyPi username.

**Comment by philass** [comment]
Just made an account. Username is philass

**Comment by pepijndevos** [comment]
Done! I've also added you as a collaborator to this repo if you need to experiment on a branch to trigger a build or something. I trust you wont do anything reckless ;-)

**Comment by pepijndevos** [comment]
I guess this never happened?

**Comment by philass** [comment]
It did not. I must have gone down some rabbit hole and forgot to get back to this. I can probably look into this later today. 

You put a fair deal of work into adding my as a contributor to PyPi and I didn't what I said I would. Super sorry about that

**Comment by pepijndevos** [comment]
Don't worry, nobody is getting paid to do any of this. I only noticed because I merged a PR and CI failed and I took a look at the open issues. But hey, if you feel like it, it'd be greatly appreciated.

**Comment by athas** [comment]
I made a few more fixes it would be nice to have on PyPI.

**Comment by athas** [comment]
Maybe [this should be automated with GA](https://github.com/pypa/gh-action-pypi-publish)?

**Comment by philass** [comment]
Would you recommend changing the whole CI to Github Actions?

**Comment by pepijndevos** [comment]
Yea, automating PyPi would be great. I've added @athas to the PyPi project. Or maybe I can find some time to do the GA stuff myself later.  I went ahead and added a `PYPI_API_TOKEN` secret for PyPi already.

**Comment by pepijndevos** [comment]
I think it'd just be a matter of copy-pasting this? But of course it always takes 5 more tries than you expect.... otherwise I'd just do it right now.

https://github.com/YosysHQ/apicula/blob/ea73897fb0cd5aae896c4d2354b653440d18d2e5/.github/workflows/chipdb.yml#L69-L86

**Comment by athas** [comment]
I'll give it a shot; I spent enough time playing with GA already.

**Comment by athas** [comment]
It works!

**Comment by pepijndevos** [comment]
Amazing :)
Looks like I was pretty spot on with my estimate of 5 tries
