### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by pepijndevos** [pepijndevos/futhark-pycffi#16]
After merging the latest PR apparently the tests broke.
https://travis-ci.org/github/pepijndevos/futhark-pycffi/jobs/760787891
It complains about this line, and I'm not sure what the correct solution is.
https://github.com/pepijndevos/futhark-pycffi/blob/fc3ecc747038c6d6d88f935fee52f4b45269d0fa/test.fut#L17

I played around a bit on the repl, and `iota` seems to expect an `i64`, while the function has an `i8` argument.
Did `i8.iota` disappear, or did the syntax change?

Ping @athas

**Comment by athas** [comment]
Yes, `i8.iota` vanished in 0.17.2.  Write it as `map i8.i64 (iota (i64.i8 a))` instead.

**Comment by pepijndevos** [comment]
Ah. Any particular reason, or just maintenance burden of maintaining copies of functions for every type?

**Comment by athas** [comment]
Yes, mostly a general principle of minimising the prelude.  With size types, they also aren't terribly useful.
